begin;

create table if not exists public.catalogs (
  id text primary key,
  name text not null,
  description text not null default '',
  route text not null,
  price_label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  description text not null default '',
  category_name text,
  image text,
  unit_of_measure text,
  sku text,
  brand text,
  stock numeric not null default 0 check (stock >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_prices (
  catalog_id text not null references public.catalogs(id) on update cascade on delete cascade,
  product_id text not null references public.products(id) on update cascade on delete cascade,
  price numeric(14, 2) not null check (price > 0),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (catalog_id, product_id)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  catalog_id text not null,
  product_id text not null,
  previous_price numeric(14, 2),
  new_price numeric(14, 2) not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists catalog_prices_catalog_order_idx
  on public.catalog_prices (catalog_id, sort_order, product_id)
  where is_active;

create index if not exists products_category_idx
  on public.products (category_name);

create index if not exists price_history_product_idx
  on public.price_history (catalog_id, product_id, changed_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_catalog_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

create or replace function public.record_price_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or old.price is distinct from new.price then
    insert into public.price_history (
      catalog_id,
      product_id,
      previous_price,
      new_price,
      changed_by
    ) values (
      new.catalog_id,
      new.product_id,
      case when tg_op = 'UPDATE' then old.price else null end,
      new.price,
      auth.uid()
    );
  end if;

  new.updated_by = auth.uid();
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists catalogs_set_updated_at on public.catalogs;
create trigger catalogs_set_updated_at
before update on public.catalogs
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists catalog_prices_record_change on public.catalog_prices;
create trigger catalog_prices_record_change
before insert or update of price on public.catalog_prices
for each row execute function public.record_price_change();

alter table public.catalogs enable row level security;
alter table public.products enable row level security;
alter table public.catalog_prices enable row level security;
alter table public.admin_users enable row level security;
alter table public.price_history enable row level security;

drop policy if exists "Public can read active catalogs" on public.catalogs;
create policy "Public can read active catalogs"
on public.catalogs for select
to anon, authenticated
using (is_active);

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);

drop policy if exists "Public can read active catalog prices" on public.catalog_prices;
create policy "Public can read active catalog prices"
on public.catalog_prices for select
to anon, authenticated
using (is_active);

drop policy if exists "Admins manage catalogs" on public.catalogs;
create policy "Admins manage catalogs"
on public.catalogs for all
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products"
on public.products for all
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Admins manage catalog prices" on public.catalog_prices;
create policy "Admins manage catalog prices"
on public.catalog_prices for all
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Admins can view own role" on public.admin_users;
create policy "Admins can view own role"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Admins read price history" on public.price_history;
create policy "Admins read price history"
on public.price_history for select
to authenticated
using (public.is_catalog_admin());

grant usage on schema public to anon, authenticated;
grant select on public.catalogs, public.products, public.catalog_prices to anon, authenticated;
grant select, insert, update, delete on public.catalogs, public.products, public.catalog_prices to authenticated;
grant select on public.admin_users, public.price_history to authenticated;
grant usage, select on sequence public.price_history_id_seq to authenticated;

insert into public.catalogs (id, name, description, route, price_label)
values
  ('whatsapp', 'Catalogo WhatsApp', 'Lista principal de packs para pedidos por WhatsApp.', '/', 'Precio por pack'),
  ('commerce-pos', 'Comercios y puntos de venta', 'Packs destinados a comercios y puntos de venta.', '/catalogo-comercios-punto-de-ventas', 'Precio por pack'),
  ('distributor-pallet', 'Distribuidora por pallet', 'Precio base por pack usado para calcular cada pallet.', '/catalogo-distribuidora-pallet', 'Precio base por pack'),
  ('wholesale', 'Catalogo mayorista', 'Lista mayorista por unidad y presentacion.', '/catalogo-mayorista', 'Precio mayorista'),
  ('retail', 'Catalogo minorista', 'Precios finales del canal minorista.', '/catalogo-minorista', 'Precio minorista'),
  ('holowaty', 'Lista Holowaty', 'Precio de lista usado para calcular descuentos y netos.', '/holowaty', 'Precio de lista')
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  route = excluded.route,
  price_label = excluded.price_label,
  is_active = true;

commit;