begin;

create table if not exists public.sales_channels (
  id text primary key,
  name text not null,
  catalog_id text references public.catalogs(id) on update cascade on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pricing_rules (
  id bigint generated by default as identity primary key,
  catalog_id text not null unique references public.catalogs(id) on update cascade on delete cascade,
  sales_channel_id text not null references public.sales_channels(id) on update cascade,
  target_margin_percent numeric(7, 4) not null check (target_margin_percent >= 0 and target_margin_percent < 100),
  tax_rate_percent numeric(7, 4) not null default 21 check (tax_rate_percent >= 0 and tax_rate_percent < 100),
  commercial_discount_percent numeric(7, 4) not null default 0 check (commercial_discount_percent >= 0 and commercial_discount_percent < 100),
  bonus_percent numeric(7, 4) not null default 0 check (bonus_percent >= 0 and bonus_percent < 100),
  maximum_discount_percent numeric(7, 4) not null default 40 check (maximum_discount_percent >= 0 and maximum_discount_percent < 100),
  minimum_price numeric(14, 2) check (minimum_price is null or minimum_price >= 0),
  minimum_pvp numeric(14, 2) check (minimum_pvp is null or minimum_pvp > 0),
  maximum_pvp numeric(14, 2) check (maximum_pvp is null or maximum_pvp > 0),
  payment_terms text not null default 'Contado',
  minimum_volume numeric(14, 2) not null default 1 check (minimum_volume > 0),
  rounding_enabled boolean not null default true,
  rounding_endings smallint[] not null default array[19, 39, 90, 99]::smallint[],
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (catalog_id in ('wholesale', 'distributor-pallet', 'commerce-pos')),
  check (maximum_pvp is null or minimum_pvp is null or maximum_pvp >= minimum_pvp),
  check (commercial_discount_percent <= maximum_discount_percent)
);

create table if not exists public.price_calculations (
  id bigint generated by default as identity primary key,
  product_id text references public.products(id) on update cascade on delete set null,
  catalog_id text not null references public.catalogs(id) on update cascade on delete cascade,
  pricing_rule_id bigint references public.pricing_rules(id) on update cascade on delete set null,
  pvp_final numeric(14, 2) not null,
  pvp_net numeric(14, 2) not null,
  sale_net numeric(14, 2) not null,
  invoiced_price numeric(14, 2) not null,
  target_margin_percent numeric(7, 4) not null,
  retailer_margin_percent numeric(7, 4) not null,
  retailer_markup_percent numeric(9, 4) not null,
  amate_internal_cost numeric(14, 2),
  amate_margin_percent numeric(9, 4),
  calculation jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (catalog_id in ('wholesale', 'distributor-pallet', 'commerce-pos'))
);

create index if not exists price_calculations_catalog_created_idx
  on public.price_calculations (catalog_id, created_at desc);

drop trigger if exists sales_channels_set_updated_at on public.sales_channels;
create trigger sales_channels_set_updated_at
before update on public.sales_channels
for each row execute function public.set_updated_at();

drop trigger if exists pricing_rules_set_updated_at on public.pricing_rules;
create trigger pricing_rules_set_updated_at
before update on public.pricing_rules
for each row execute function public.set_updated_at();

create or replace function public.calculate_commercial_price(
  p_pvp_final numeric,
  p_tax_rate_percent numeric,
  p_target_margin_percent numeric,
  p_list_price_net numeric default null,
  p_discount_percent numeric default 0,
  p_bonus_percent numeric default 0,
  p_amate_internal_cost numeric default null
)
returns jsonb
language plpgsql
immutable
security invoker
set search_path = public
as $$
declare
  v_pvp_net numeric(14, 2);
  v_maximum_sale_net numeric(14, 2);
  v_list_price_net numeric(14, 2);
  v_sale_net numeric(14, 2);
  v_b2b_tax numeric(14, 2);
  v_invoiced_price numeric(14, 2);
  v_retailer_profit numeric(14, 2);
  v_retailer_margin numeric(9, 4);
  v_retailer_markup numeric(9, 4);
  v_amate_profit numeric(14, 2);
  v_amate_margin numeric(9, 4);
begin
  if p_pvp_final <= 0 then raise exception 'El PVP final debe ser mayor que cero'; end if;
  if p_tax_rate_percent < 0 or p_tax_rate_percent >= 100 then raise exception 'IVA fuera de rango'; end if;
  if p_target_margin_percent < 0 or p_target_margin_percent >= 100 then raise exception 'Margen fuera de rango'; end if;
  if p_discount_percent < 0 or p_discount_percent >= 100 then raise exception 'Descuento fuera de rango'; end if;
  if p_bonus_percent < 0 or p_bonus_percent >= 100 then raise exception 'Bonificacion fuera de rango'; end if;

  v_pvp_net := round(p_pvp_final / (1 + p_tax_rate_percent / 100), 2);
  v_maximum_sale_net := round(v_pvp_net * (1 - p_target_margin_percent / 100), 2);
  v_list_price_net := coalesce(p_list_price_net, v_maximum_sale_net);
  v_sale_net := round(v_list_price_net * (1 - p_discount_percent / 100) * (1 - p_bonus_percent / 100), 2);
  v_b2b_tax := round(v_sale_net * p_tax_rate_percent / 100, 2);
  v_invoiced_price := v_sale_net + v_b2b_tax;
  v_retailer_profit := v_pvp_net - v_sale_net;
  v_retailer_margin := round(v_retailer_profit / nullif(v_pvp_net, 0) * 100, 4);
  v_retailer_markup := round(v_retailer_profit / nullif(v_sale_net, 0) * 100, 4);
  v_amate_profit := case when p_amate_internal_cost is null then null else v_sale_net - p_amate_internal_cost end;
  v_amate_margin := case when v_amate_profit is null then null else round(v_amate_profit / nullif(v_sale_net, 0) * 100, 4) end;

  return jsonb_build_object(
    'pvpFinal', round(p_pvp_final, 2),
    'pvpNet', v_pvp_net,
    'targetMarginPercent', p_target_margin_percent,
    'maximumSaleNet', v_maximum_sale_net,
    'listPriceNet', v_list_price_net,
    'commercialDiscountPercent', p_discount_percent,
    'bonusPercent', p_bonus_percent,
    'saleNet', v_sale_net,
    'b2bTax', v_b2b_tax,
    'invoicedPrice', v_invoiced_price,
    'retailerGrossProfit', v_retailer_profit,
    'retailerGrossMarginPercent', v_retailer_margin,
    'retailerMarkupPercent', v_retailer_markup,
    'amateInternalCost', p_amate_internal_cost,
    'amateGrossProfit', v_amate_profit,
    'amateGrossMarginPercent', v_amate_margin
  );
end;
$$;

alter table public.sales_channels enable row level security;
alter table public.pricing_rules enable row level security;
alter table public.price_calculations enable row level security;

drop policy if exists "Public reads sales channels" on public.sales_channels;
create policy "Public reads sales channels" on public.sales_channels
for select to anon, authenticated using (is_active);

drop policy if exists "Public reads active pricing rules" on public.pricing_rules;
create policy "Public reads active pricing rules" on public.pricing_rules
for select to anon, authenticated using (is_active);

drop policy if exists "Admins manage sales channels" on public.sales_channels;
create policy "Admins manage sales channels" on public.sales_channels
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

drop policy if exists "Admins manage pricing rules" on public.pricing_rules;
create policy "Admins manage pricing rules" on public.pricing_rules
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

drop policy if exists "Admins manage price calculations" on public.price_calculations;
create policy "Admins manage price calculations" on public.price_calculations
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

grant select on public.sales_channels, public.pricing_rules to anon, authenticated;
grant select, insert, update, delete on public.sales_channels, public.pricing_rules, public.price_calculations to authenticated;
grant usage, select on sequence public.pricing_rules_id_seq, public.price_calculations_id_seq to authenticated;
grant execute on function public.calculate_commercial_price(numeric, numeric, numeric, numeric, numeric, numeric, numeric) to anon, authenticated;

insert into public.sales_channels (id, name, catalog_id) values
  ('supermarket', 'Supermercado', 'wholesale'),
  ('wholesaler', 'Mayorista', 'wholesale'),
  ('self-service', 'Autoservicio', 'commerce-pos'),
  ('grocery', 'Almacen', 'commerce-pos'),
  ('health-store', 'Dietetica', 'commerce-pos'),
  ('distributor', 'Distribuidor', 'distributor-pallet'),
  ('special-client', 'Cliente especial', null)
on conflict (id) do update set name = excluded.name, catalog_id = excluded.catalog_id, is_active = true;

insert into public.pricing_rules (
  catalog_id, sales_channel_id, target_margin_percent, tax_rate_percent,
  maximum_discount_percent, payment_terms, minimum_volume
) values
  ('wholesale', 'wholesaler', 20, 21, 40, 'Contado', 10),
  ('distributor-pallet', 'distributor', 15, 21, 40, 'Contado', 1),
  ('commerce-pos', 'self-service', 25, 21, 40, 'Contado', 1)
on conflict (catalog_id) do nothing;

commit;